---
title: "Study1(3c3e)_short_timeframe_analysis"
author: "Yiwen Zhang"
date: "2024-09-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(BayesFactor)
library(lmerTest)
library(ggsignif)
library(ggh4x)

plot_theme <- theme(
  panel.margin.y = unit(2, "lines"),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  text = element_text(size = 16),
  strip.background = element_rect(fill = "white", color = "white"),
  strip.placement = "outside")
```

```{r}
# import data
study0.short1 <- read.csv("/Users/YIZ173/Documents/GitHub/delay_intervening_events_studies/Experiment_1a_1b/exp1a-clean-data.csv")

# calculate different score
study0.short.diff.subj <- study0.short1 %>% 
  group_by(dataset, task_id, rel_type, intvn, cause_num) %>%
  summarise(cs_value = mean(causal_strength)) %>%
  pivot_wider(names_from = rel_type, values_from = cs_value) %>%
  mutate(diff = veridical - nonVeridical)

# preparing data for short vs long comparison
# study0.short.diff.subj %>%
#   subset(dataset == "three_pos_10_2_0_12.csv") %>%
#   write.csv("study1-short-diff_83.csv")

# study0.short.diff.subj
```


# Testing for Successful Learning: Veridical vs nonVeridical

```{r pressure, echo=FALSE, fig.height=3, fig.width=12}
# subject-level mean causal strength
study0.short1.subj <- study0.short1 %>% 
  group_by(dataset, task_id, rel_type, intvn) %>%
  summarise(cs_value = mean(causal_strength))

# paired t tests
study0.short1.subj %>%
  pivot_wider(names_from = rel_type, values_from = cs_value) %>%
  group_by(dataset) %>%
  summarise(
    t = t.test(x = veridical, y = nonVeridical, paired = T, alternative = "two.sided")$statistic,
    t.p.value = round(t.test(x = veridical, y = nonVeridical, paired = T, alternative = "two.sided")$p.value,3),
    cohen.d = round( (mean(veridical) - mean(nonVeridical)) / sd(veridical), 3),
    V = wilcox.test(x = veridical, y = nonVeridical, paired = T, alternative = "two.sided",exact = F)$statistic,
    wilcox.p = wilcox.test(x = veridical, y = nonVeridical, paired = T, alternative = "two.sided",exact = F)$p.value,
    ttestBF = round( exp(ttestBF(x = veridical, y = nonVeridical, paired = T)@bayesFactor$bf), 3)
  ) %>%
  arrange(ttestBF) %>%
  # adjusting p values
  mutate(t.p_adjust = p.adjust(t.p.value, method="BH"),
         wilcox.p_adjust = p.adjust(wilcox.p, method="BH")) -> rel_type_test

# results output
rel_type_test$dataset = factor(rel_type_test$dataset, label = c("Contingency = 0.83", "Contingency = 0.67", "Contingency = 0.50"))
rel_type_test
```

# Figure of Exp 1a Veridical vs NonVeridical

```{r}
study0.short1 %>% 
  group_by(dataset, task_id, rel_type, intvn, cause_num) %>%
  summarise(cs_value = mean(causal_strength)) %>%
  group_by(dataset, rel_type, cause_num, intvn) %>%
  summarise(
    mean = t.test(cs_value, mu = 0, alternative = "two.sided")$estimate,
    lower = t.test(cs_value, mu = 0, alternative = "two.sided")$conf.int[1],
    upper = t.test(cs_value, mu = 0, alternative = "two.sided")$conf.int[2]
    ) -> rel_type_bycond_smry

rel_type_bycond_smry$rel_type = factor(rel_type_bycond_smry$rel_type, levels = c("veridical", "nonVeridical"), label = c("Veridical", "Non Veridical"))

rel_type_bycond_smry$dataset = factor(rel_type_bycond_smry$dataset, label = c("\u0394P = 0.83", "\u0394P = 0.67", "\u0394P = 0.50"))

rel_type_bycond_smry %>%
    mutate(cause_name = ifelse(intvn > 0 , paste0(toupper(cause_num), "\n(",intvn, " ICs)"), paste0(toupper(cause_num), "\n(",intvn, " IC)"))) %>%
  ggplot(aes(x = factor(intvn), y = mean, color = rel_type, group = rel_type)) +
  geom_point(position = position_dodge(width = 0.5)) +
  geom_errorbar(position = position_dodge(width = 0.5), aes(ymin = lower, ymax = upper), width = 0.3) +
  theme_bw() +
  plot_theme +
  scale_color_manual(values = c("lightblue","#1E5162")) +
  theme(legend.position = "bottom") +
    ylim(0,10) +
  facet_grid2(~dataset, scales = "free") +
  labs(x = "# of Intervening Causes", y = "Causal Strength", color = "") -> p0
 p0
# ggsave("../figures/study1_short_veriVSNonveri_delayIntervene.png",
#   plot = p0,
#   scale = 3,
#   width = 500,
#   height = 300,
#   units = c("px"),
#   dpi = 300)

```

# Figure of Exp 1a difference score (not in the manuscript)

```{r fig.height=3, fig.width=8}
study0.short.diff.subj %>%
  group_by(dataset, cause_num, intvn) %>%
  summarise(
    mean = t.test(diff, mu = 0, alternative = "two.sided")$estimate,
    lower = t.test(diff, mu = 0, alternative = "two.sided")$conf.int[1],
    upper = t.test(diff, mu = 0, alternative = "two.sided")$conf.int[2],
    t.p.value = round(t.test(diff, mu = 0, alternative = "two.sided")$p.value,3),
    wilcox.p = wilcox.test(diff, mu = 0, alternative = "two.sided",exact = F)$p.value,
    ttestBF = round( exp(ttestBF(diff, mu = 0)@bayesFactor$bf), 3)
    ) -> diff_smry

diff_smry$dataset = factor(diff_smry$dataset, label = c("Contingency = 0.83", "Contingency = 0.67", "Contingency = 0.50"))

diff_smry %>%
  mutate(intvn = as.numeric(as.character(intvn))) %>%
  mutate(cause_name = ifelse(intvn > 0 , paste0("C", cause_num, "\n(",intvn, " ICs)"), paste0("C", cause_num, "\n(",intvn, " IC)"))) %>%
  ggplot(aes(x = intvn, y = mean)) +
  geom_col(fill = "lightgrey") +
  geom_errorbar(position = position_dodge(width = 0.2), aes(ymin = lower, ymax = upper), width = 0.3) +
  theme_bw() +
  facet_wrap(~dataset, scales="free") +
  plot_theme +
  scale_y_continuous(limits = c(0,3)) +
  labs(x = "", y = "Difference Score", color = "") -> p1

p1

# ggsave("../figures/study1_short_diff_score_intvn.png",
#   plot = p1,
#   scale = 3,
#   width = 800,
#   height = 300,
#   units = c("px"),
#   dpi = 300)
```


# ANOVA test for the impact of Intervening events

```{r}
anova_results <- list()
friedman_results <- list()
bayes_factor_results <- list()

# repeat anova measure to test if there is any difference in difference scores
study0.short.diff.subj$intvn = factor(study0.short.diff.subj$intvn)
datasets_list = unique(study0.short.diff.subj$dataset)
for (i in 1:3) {
  # ANOVA
  anova_model <- aov(diff ~ intvn + Error(task_id/intvn), data=subset(study0.short.diff.subj, dataset == datasets_list[i]))
  anova_summary <- summary(anova_model)
  
  # Effect Size
  ss_effect <- anova_summary[[2]][[1]]["intvn", "Sum Sq"]
  ss_effect_error <- anova_summary[[2]][[1]]["Residuals", "Sum Sq"]
  # Partial eta squared
  eta_squared_partial <- ss_effect / (ss_effect + ss_effect_error)
  
  anova_df <- anova_summary[[2]][[1]]$Df
  anova_f_value <- anova_summary[[2]][[1]]$`F value`[1]
  anova_p_value <- anova_summary[[2]][[1]]$`Pr(>F)`[1]
  anova_results[[i]] <- list(df = anova_df, F_value = anova_f_value, p_value = anova_p_value, eta_squared_partial = eta_squared_partial)
  
  # non parametric test: Friedman Test
  friedman_test <- friedman.test(diff ~ intvn | task_id, data=subset(study0.short.diff.subj, dataset == datasets_list[i]))
  # print(friedman_test)
  
  # Bayes Factor
  bf_subset = subset(study0.short.diff.subj, dataset == datasets_list[i])
  bf_subset$task_id = factor(bf_subset$task_id)
  bf_model = anovaBF(diff ~ intvn + task_id, data=bf_subset, 
             whichRandom="task_id")

  friedman_results[[i]] <- list(chi_squared = friedman_test$statistic, p_value = friedman_test$p.value)
  bayes_factor_results[[i]] <- extractBF(bf_model)$bf
}
# Create a summary table
summary_table <- data.frame(
  Group = datasets_list,
  ANOVA_df = sapply(anova_results, function(x) paste(x$df, collapse = ", ")),
  ANOVA_F = sapply(anova_results, function(x) round(x$F_value, 3)),
  ANOVA_p_value = sapply(anova_results, function(x) round(x$p_value, 3)),
  eta_squared_partial = sapply(anova_results, function(x) round(x$eta_squared_partial, 3)),
  Friedman_chi_squared = sapply(friedman_results, function(x) round(x$chi_squared, 3)),
  Friedman_p_value = sapply(friedman_results, function(x) round(x$p_value, 3)),
  Bayes_Factor = sapply(bayes_factor_results, function(x) round(x, 3))
)

# Print the table to copy and paste
summary_table %>%
  mutate(ANOVA_p_adjust = p.adjust(ANOVA_p_value, method="BH"),
         Friedman_p_adjust = p.adjust(Friedman_p_value, method="BH")) 
```




